# Sparse Matrix Multiplication Benchmark Configuration

# Test matrices configurations
matrix_sizes:
  small: [512, 1024, 1536]
  medium: [2048, 3072, 4096]
  large: [6144, 8192]

# Sparsity levels to test
sparsity_levels: [0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 0.99]

# Tile sizes to test
tile_sizes: [16, 32]

# Number of warmup runs
warmup_runs: 3

# Number of measurement runs (for averaging)
measurement_runs: 5

# Output configuration
output:
  results_dir: "results"
  reports_dir: "reports"
  save_raw_data: true
  generate_plots: true
  generate_html_report: true

# Executable configuration
executable:
  path: "../sparse_mm_benchmark"
  build_command: "cd .. && make clean && make"

# Plot configuration
plots:
  width: 1200
  height: 800
  dpi: 300
  style: "seaborn-v0_8"
  color_palette: "husl"

# CI/Performance thresholds
thresholds:
  max_regression: 0.1  # 10% performance regression threshold
  min_speedup: 0.5     # Minimum expected speedup for sparse vs dense